transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlib WiPhase_top_level
vmap WiPhase_top_level WiPhase_top_level
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_avalon_st_adapter_001.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_avalon_st_adapter.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_mm_interconnect_0.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/altera_avalon_sc_fifo.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_timer.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_test_pattern_st_gen.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_test_pattern_st_gen_command_fifo.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_test_pattern_st_gen_position_ram.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_test_pattern_st_gen_packetcount_ram.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_sysid.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_spi.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_sample_pll.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_ram_onchip.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_jtag_uart.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_eth.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_cpu_v2.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_cpu_v2_cpu.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_cpu_v2_cpu_debug_slave_sysclk.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_cpu_v2_cpu_debug_slave_tck.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_cpu_v2_cpu_debug_slave_wrapper.v}
vlog -vlog01compat -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_cpu_v2_cpu_test_bench.v}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_avalon_st_adapter_001_timing_adapter_1.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_avalon_st_adapter_001_timing_adapter_0.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_avalon_st_adapter_001_timing_adapter_0_fifo.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_avalon_st_adapter_001_error_adapter_0.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_avalon_st_adapter_001_data_format_adapter_0.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_avalon_st_adapter_error_adapter_0.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_avalon_st_adapter_data_format_adapter_0.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_irq_mapper.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_mm_interconnect_0_rsp_mux_001.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_mm_interconnect_0_cmd_mux_005.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_mm_interconnect_0_cmd_demux_001.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_mm_interconnect_0_router_007.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_mm_interconnect_0_router_002.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_mm_interconnect_0_router_001.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/WiPhase_top_level_mm_interconnect_0_router.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/altera_merlin_master_agent.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work WiPhase_top_level +incdir+C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/altera_merlin_master_translator.sv}
vcom -2008 -work WiPhase_top_level {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/WiPhase_top_level.vhd}
vcom -2008 -work WiPhase_top_level {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_top_level/synthesis/submodules/Debug_ST_Sink.vhd}
vcom -2008 -work work {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_phys.vhd}
vcom -2008 -work work {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/clock_divider.vhd}

vcom -2008 -work work {C:/Users/alist/OneDrive/Electrickery/Phased-Array-Radio-Telescope/Phased-Array-WiFi-Camera/FPGA_Firmware/WiPhase_phys_tst.vht}

vsim -t 1ps -L altera -L lpm -L sgate -L altera_mf -L altera_lnsim -L cyclone10lp -L rtl_work -L work -L WiPhase_top_level -voptargs="+acc"  WiPhase_phys_vhd_tst

add wave *
view structure
view signals
run 1000 ns
