	rgmii_ethernet u0 (
		.clk           (<connected-to-clk>),           // control_port_clock_connection.clk
		.reset         (<connected-to-reset>),         //              reset_connection.reset
		.reg_addr      (<connected-to-reg_addr>),      //                  control_port.address
		.reg_data_out  (<connected-to-reg_data_out>),  //                              .readdata
		.reg_rd        (<connected-to-reg_rd>),        //                              .read
		.reg_data_in   (<connected-to-reg_data_in>),   //                              .writedata
		.reg_wr        (<connected-to-reg_wr>),        //                              .write
		.reg_busy      (<connected-to-reg_busy>),      //                              .waitrequest
		.tx_clk        (<connected-to-tx_clk>),        //   pcs_mac_tx_clock_connection.clk
		.rx_clk        (<connected-to-rx_clk>),        //   pcs_mac_rx_clock_connection.clk
		.set_10        (<connected-to-set_10>),        //         mac_status_connection.set_10
		.set_1000      (<connected-to-set_1000>),      //                              .set_1000
		.eth_mode      (<connected-to-eth_mode>),      //                              .eth_mode
		.ena_10        (<connected-to-ena_10>),        //                              .ena_10
		.ff_rx_clk     (<connected-to-ff_rx_clk>),     //      receive_clock_connection.clk
		.ff_tx_clk     (<connected-to-ff_tx_clk>),     //     transmit_clock_connection.clk
		.ff_rx_data    (<connected-to-ff_rx_data>),    //                       receive.data
		.ff_rx_eop     (<connected-to-ff_rx_eop>),     //                              .endofpacket
		.rx_err        (<connected-to-rx_err>),        //                              .error
		.ff_rx_mod     (<connected-to-ff_rx_mod>),     //                              .empty
		.ff_rx_rdy     (<connected-to-ff_rx_rdy>),     //                              .ready
		.ff_rx_sop     (<connected-to-ff_rx_sop>),     //                              .startofpacket
		.ff_rx_dval    (<connected-to-ff_rx_dval>),    //                              .valid
		.ff_tx_data    (<connected-to-ff_tx_data>),    //                      transmit.data
		.ff_tx_eop     (<connected-to-ff_tx_eop>),     //                              .endofpacket
		.ff_tx_err     (<connected-to-ff_tx_err>),     //                              .error
		.ff_tx_mod     (<connected-to-ff_tx_mod>),     //                              .empty
		.ff_tx_rdy     (<connected-to-ff_tx_rdy>),     //                              .ready
		.ff_tx_sop     (<connected-to-ff_tx_sop>),     //                              .startofpacket
		.ff_tx_wren    (<connected-to-ff_tx_wren>),    //                              .valid
		.xon_gen       (<connected-to-xon_gen>),       //           mac_misc_connection.xon_gen
		.xoff_gen      (<connected-to-xoff_gen>),      //                              .xoff_gen
		.magic_wakeup  (<connected-to-magic_wakeup>),  //                              .magic_wakeup
		.magic_sleep_n (<connected-to-magic_sleep_n>), //                              .magic_sleep_n
		.ff_tx_crc_fwd (<connected-to-ff_tx_crc_fwd>), //                              .ff_tx_crc_fwd
		.ff_tx_septy   (<connected-to-ff_tx_septy>),   //                              .ff_tx_septy
		.tx_ff_uflow   (<connected-to-tx_ff_uflow>),   //                              .tx_ff_uflow
		.ff_tx_a_full  (<connected-to-ff_tx_a_full>),  //                              .ff_tx_a_full
		.ff_tx_a_empty (<connected-to-ff_tx_a_empty>), //                              .ff_tx_a_empty
		.rx_err_stat   (<connected-to-rx_err_stat>),   //                              .rx_err_stat
		.rx_frm_type   (<connected-to-rx_frm_type>),   //                              .rx_frm_type
		.ff_rx_dsav    (<connected-to-ff_rx_dsav>),    //                              .ff_rx_dsav
		.ff_rx_a_full  (<connected-to-ff_rx_a_full>),  //                              .ff_rx_a_full
		.ff_rx_a_empty (<connected-to-ff_rx_a_empty>), //                              .ff_rx_a_empty
		.rgmii_in      (<connected-to-rgmii_in>),      //          mac_rgmii_connection.rgmii_in
		.rgmii_out     (<connected-to-rgmii_out>),     //                              .rgmii_out
		.rx_control    (<connected-to-rx_control>),    //                              .rx_control
		.tx_control    (<connected-to-tx_control>)     //                              .tx_control
	);

