# TCL File Generated by Component Editor 17.1
# Mon Aug 13 11:36:53 EST 2018
# DO NOT MODIFY


# 
# Debug_ST_Sink "Debug_ST_Sink" v1.0
#  2018.08.13.11:36:53
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Debug_ST_Sink
# 
set_module_property DESCRIPTION ""
set_module_property NAME Debug_ST_Sink
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Debug_ST_Sink
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 


# 
# connection point ST_sink_connection
# 
add_interface ST_sink_connection avalon_streaming end
set_interface_property ST_sink_connection dataBitsPerSymbol 8
set_interface_property ST_sink_connection errorDescriptor ""
set_interface_property ST_sink_connection firstSymbolInHighOrderBits true
set_interface_property ST_sink_connection maxChannel 0
set_interface_property ST_sink_connection readyLatency 0
set_interface_property ST_sink_connection ENABLED true
set_interface_property ST_sink_connection EXPORT_OF ""
set_interface_property ST_sink_connection PORT_NAME_MAP ""
set_interface_property ST_sink_connection CMSIS_SVD_VARIABLES ""
set_interface_property ST_sink_connection SVD_ADDRESS_GROUP ""

add_interface_port ST_sink_connection ST_sink_connection_data data Input 8
add_interface_port ST_sink_connection ST_sink_connection_endofpacket endofpacket Input 1
add_interface_port ST_sink_connection ST_sink_connection_startofpacket startofpacket Input 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1

